#337 Исправлена ошибка настройки NAT в pjsip.conf. Добавлена проверка версии Linux при начале работы контейнера. Добавлено заполнение таблицы сетевых интерфейсов.

diff --git a/resources/rootfs/sbin/docker-entrypoint b/resources/rootfs/sbin/docker-entrypoint
--- a/resources/rootfs/sbin/docker-entrypoint
+++ b/resources/rootfs/sbin/docker-entrypoint
@@ -1,5 +1,12 @@
 #!/bin/sh
 
+kernelVersion="$(/bin/uname -r | /bin/cut -f 1 -d '.')";
+
+if [ ! "$kernelVersion" = '5' ]; then
+  echo 'ERROR: Only linux 5 is supported...';
+  exit 4;
+fi
+
 cleanup()
 {
   echoToTeletype "Receive signal to restart "...;
