Исправил ошибку обновления АТС c 2024.2.130 на 2024.2.140+.

diff --git a/src/Core/System/RootFS/sbin/check-update-pbx b/src/Core/System/RootFS/sbin/check-update-pbx
--- a/src/Core/System/RootFS/sbin/check-update-pbx
+++ b/src/Core/System/RootFS/sbin/check-update-pbx
@@ -18,7 +18,7 @@
 . /sbin/shell_functions.sh;
 
 systemDir='/system';
-mkdir "$systemDir";
+mkdir -p "$systemDir";
 
 # Function to mount disks smaller than 60MB
 searchNewFirmware() {
@@ -27,22 +27,20 @@ searchNewFirmware() {
   # Iterate over the block devices.
   for disk in $list; do
     size="$(/bin/lsblk "$disk" -P -b -o SIZE | /bin/busybox cut -f 2 -d '"' | /bin/busybox cut -f 1 -d 'M')";
-    # Skip disks larger than 60MB.
-    if [ "$(printf "%.0f\n" "$((size / 1024 / 1024))")" -gt 60 ]; then
+    if [ "$(printf "%.0f\n" "$((size / 1024 / 1024))")" -gt 101 ]; then
+       echo " - Skip disks larger than 101MB. ";
        continue;
     fi
-
     # Mount the disk to the system directory if it less than 60 mb
     mount "$disk" "$systemDir";
     MOUNT_RESULT=$?;
     if [ ! "${MOUNT_RESULT}" = "0" ] ; then
+      echo " - Fail mount $disk to $systemDir...";
       continue;
     fi
     checkAndUpgrade "$disk";
-
     # Umount boot disk
     umount -f "$disk";
-
   done
 }
 
@@ -57,23 +55,22 @@ checkAndUpgrade() {
 
     # Move files to prevent cycle
     mv "$updateFolder" /tmp
-    cd /tmp/upgrade
+    cd /tmp/upgrade || exit 1;
 
     # Inform user and allow interrupting the upgrade process
-    echo "Found a new MikoPBX firmware."
-    echo "Press 'c' to cancel the upgrade or wait 10 seconds to continue."
+    echo " - Found a new MikoPBX firmware."
+    echo " - Press 'c' to cancel the upgrade or wait 10 seconds to continue."
     local counter=10
     while [ $counter -gt 0 ]; do
-      read -t 1 -n 1 input
+      read -r -t 1 -n 1 input
       if [ "$input" = "C" ] || [ "$input" = "c" ]; then
-        echo "Upgrade cancelled by user."
+        echo " - Upgrade cancelled by user."
         return 1  # Exit the function early if 'c' is pressed
       fi
-      echo -ne "Continuing in $counter seconds...\033[0K\r"
+      echo -ne " - Continuing in $counter seconds...\033[0K\r"
       counter=$((counter - 1))
     done
-    echo "Starting upgrade process..."
-
+    echo " - Starting upgrade process..."
     # Umount boot disk
     umount -f "$disk";
 
