Optimize recovery/installation process

diff --git a/src/Core/System/RootFS/sbin/initial_storage_part_four b/src/Core/System/RootFS/sbin/initial_storage_part_four
--- a/src/Core/System/RootFS/sbin/initial_storage_part_four
+++ b/src/Core/System/RootFS/sbin/initial_storage_part_four
@@ -18,9 +18,11 @@
 #
 
 # Check whether the script has been run with the "create" argument; if not, exit with status code 6
-if [ "$1" != "create" ];then
-	exit 6;
-fi;
+action="$1"
+if [ "$action" != "create" ] && [ "$action" != "update" ]; then
+    echo "Invalid argument: $1. Please use 'create' or 'update'."
+    exit 6
+fi
 
 # If the second argument is not given, we'll use the device specified in the file /var/etc/cfdevice
 # Otherwise, we use the device specified as the second argument
@@ -38,26 +40,21 @@ fi;
 
 # Check if the device exists and is a block device
 if [ ! -b "${dev}" ];then
+  echo "Device ${dev} doesn't exist or isn't a block device."
 	exit 4; # If the device doesn't exist or isn't a block device, exit with status code 4
-fi;
-
-# Check if the device is mounted
-mounted=$(mount | /bin/busybox grep "${dev}");
-if [ "${mounted}x" != "x" ];then
-	exit 7;  #If the device is mounted, exit with status code 7
 fi;
 
 # Get the total size of the device in MB
 totalMb=$(($(busybox blockdev --getsize64 "${dev}") / 1024 / 1024));
 
 if [ "$totalMb" -le "600" ]; then
-   # If the device size is less than or equal to 600 MB, there's no point in creating a 4th partition.
+  echo "Device ${dev} size is less than or equal to 600 MB, there's no point in creating a 4th partition."
   exit 0;
 fi
 
 # Get partition info for the device
 count=$(/sbin/sfdisk -l "${dev}" | /bin/busybox grep "^/dev" | /bin/busybox wc -l);
-if [ "$count" -eq "4" ]; then
+if [ "$count" -eq "4" ] && [ "$action" == "create" ]; then
     # The fourth partition already exists, format it and resize
     partitionName=$(/bin/lsblk -r | /bin/busybox grep "$(/bin/busybox basename "$dev")" |  /bin/busybox cut -d ' ' -f 1 | /bin/busybox grep "4$" | /bin/sort -u);
     partitionFour="/dev/${partitionName}";
@@ -123,6 +120,10 @@ if [ "$resultParted" = "0" ];then
         mkfsResult=$?;
         if [ "$mkfsResult" != "0" ]; then
             echo " - ERROR: mkfs on '${partitionFour}' type '${type}' exit code '$mkfsResult'"
+
+        else
+           sleep 3;
+           resize2fs /dev/sda4
         fi;
 
         # Get the UUID of the new partition
